 services:
   fastapi_app:
     command: uvicorn main:app --port 8030 --reload --host 0.0.0.0
     build:
       context: .
       dockerfile: dockerfile
     environment:
       PYTHONUNBEFFERED: 1
     container_name: api
     ports:
       - "8030:8030"
     volumes:
       - .:/usr/src/app:rw
     depends_on:
       - qdrant

   qdrant:
     image: qdrant/qdrant
     ports:
       - "6333:6333"
     environment:
      # Optionally pass any Qdrant configuration via env variables.
      - QDRANT__PORT=6333